### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'headers'

### ISSUE THREAD

**Issue by Colgaton** [fboender/mod_sec_report#1]
Any idea what can this be? Using python3.8:

./mod_sec_report /var/log/apache2/modsec_audit.log
Traceback (most recent call last):
  File "./mod_sec_report", line 113, in <module>
    output(sorted(entries, key=lambda entry: entry["transaction"]["time_parsed"]))
  File "./mod_sec_report", line 96, in output
    print(template.render(entries=entries))
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 131, in top-level template code
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'headers'

**Comment by fboender** [comment]
Looks like it relates to this line in the template:

```
                        {% for header_k, header_v in entry["response"]["headers"].items() %}
```

Maybe there's a response in the JSON without any headers? Would be weird though; I've never seen that happen.

Anyway, I've pushed a change that doesn't crash when the response has no headers. Can you try again with the latest master?

**Comment by Colgaton** [comment]
Yep it seems to work now, thank you.
